//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ID_Chat { get; set; }
        public int ID_Sender { get; set; }
        public int ID_Receiver { get; set; }
        public string Message { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
