//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Plugin
    {
        public int ID_Comment_Plugin { get; set; }
        public string Content_Comment { get; set; }
        public System.DateTime Date_Comment { get; set; }
        public int ID_Plugin { get; set; }
        public int ID_User { get; set; }
    
        public virtual Plugins Plugins { get; set; }
        public virtual User User { get; set; }
    }
}
