//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int ID_Feedback { get; set; }
        public System.DateTime Date_Comment { get; set; }
        public string Comment { get; set; }
        public int ID_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
