//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_Music
    {
        public int ID_Price_Music { get; set; }
        public int Price { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_Music { get; set; }
    
        public virtual Music Music { get; set; }
    }
}
