//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_Music
    {
        public int ID_Price_Music { get; set; }
        public int Price { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_Music { get; set; }
    
        public virtual Music Music { get; set; }
    }
}
