//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int ID_Comments { get; set; }
        public string Content_Сomments { get; set; }
        public System.DateTime Data_Comments { get; set; }
        public Nullable<int> ID_Music { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> ID_Plugin { get; set; }
    
        public virtual Music Music { get; set; }
        public virtual Plugins Plugins { get; set; }
        public virtual User User { get; set; }
    }
}
