//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Music
    {
        public int ID_Order_Music { get; set; }
        public int ID_Music { get; set; }
        public int ID_User { get; set; }
    
        public virtual Music Music { get; set; }
        public virtual User User { get; set; }
    }
}
