//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Plugin
    {
        public int ID_Order_Plugin { get; set; }
        public int ID_Plugin { get; set; }
        public int ID_User { get; set; }
    
        public virtual Plugins Plugins { get; set; }
        public virtual User User { get; set; }
    }
}
