//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price_Plugin
    {
        public int ID_Price_Plugin { get; set; }
        public int Price { get; set; }
        public System.DateTime Date { get; set; }
        public int ID_Plugin { get; set; }
    
        public virtual Plugins Plugins { get; set; }
    }
}
