//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Alboms = new HashSet<Alboms>();
            this.Comments = new HashSet<Comments>();
            this.Music = new HashSet<Music>();
            this.Сhat = new HashSet<Сhat>();
            this.Сhat1 = new HashSet<Сhat>();
        }
    
        public int ID_User { get; set; }
        public string Last_Name_User { get; set; }
        public string First_Name_User { get; set; }
        public string Middle_Name_User { get; set; }
        public string Description_User { get; set; }
        public Nullable<int> Age_User { get; set; }
        public byte[] Image_User { get; set; }
        public string Nickname_User { get; set; }
        public string Login { get; set; }
        public byte[] Password_Hash { get; set; }
        public byte[] Salt { get; set; }
        public int ID_User_Type { get; set; }
        public string Email_User { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alboms> Alboms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Music> Music { get; set; }
        public virtual User_Type User_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сhat> Сhat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сhat> Сhat1 { get; set; }
    }
}
