//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID_User { get; set; }
        public string Last_Name_User { get; set; }
        public string First_Name_User { get; set; }
        public string Middle_Name_User { get; set; }
        public string Description_User { get; set; }
        public Nullable<int> Age_User { get; set; }
        public byte[] Image_User { get; set; }
        public string Nickname_User { get; set; }
        public string Login { get; set; }
        public byte[] Password_Hash { get; set; }
        public byte[] Salt { get; set; }
        public int ID_User_Type { get; set; }
        public string Email_User { get; set; }
    
        public virtual User_Type User_Type { get; set; }
    }
}
