//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID_User { get; set; }
        public string Last_Name_User { get; set; }
        public string First_Name_User { get; set; }
        public string Middle_Name_User { get; set; }
        public string Description_User { get; set; }
        public Nullable<int> Age_User { get; set; }
        public byte[] Image_User { get; set; }
        public string Nickname_User { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> ID_User_Type { get; set; }
        public string Email_User { get; set; }
    
        public virtual User_Type User_Type { get; set; }
    }
}
