//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version_Plugins
    {
        public int ID_Version { get; set; }
        public int Version_Number { get; set; }
        public int ID_Plugin { get; set; }
    
        public virtual Plugins Plugins { get; set; }
    }
}
