//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сhat
    {
        public int ID_Chat { get; set; }
        public int ID_User1 { get; set; }
        public int ID_User2_ { get; set; }
        public bool IsFirstTyping_Chat { get; set; }
        public string Message_Char { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
